site_name: OpenAleph Procrastinate
site_url: https://openaleph.org/docs/lib/openaleph-procrastinate
repo_url: https://github.com/openaleph/openaleph-procrastinate
nav:
  - Intro: index.md
  - architecture.md
  - howto.md
  - conventions.md
  - setup.md
  - The Job model: job.md
  - Job priorities: priority.md
  - Reference:
    - defer: reference/defer.md
    - command line: reference/cli.md
    - model: reference/model.md
    - helpers: reference/helpers.md
    - settings: reference/settings.md
    - manage: reference/manage.md
theme:
  name: material
  logo: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
  favicon: https://cdn.investigativedata.org/style/logos/darc/favicon.ico
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/mail
      link: mailto:hi@dataresearchcenter.org
    - icon: material/web
      link: https://dataresearchcenter.org
    - icon: material/github
      link: https://github.com/openaleph/openaleph-procrastinate
    - icon: material/linkedin
      link: https://www.linkedin.com/company/dataresearchcenter/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - autorefs
  - mkdocs-typer2:
      pretty: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: false
            show_object_full_path: false
